name: MinigamePlugin
version: ${version}
main: me.sirsam.minigameplugin.Main
description: Minigames Plugin
author: SirSam
api-version: "1.20"

commands:
  rl:
    description: Reloads the server.
    permission: op
    permission-message: You do not have permission to use this Command!
    usage: /<command>
  shop:
    description: Opens the shop menu.
    permission: op
    permission-message: You do not have permission to use this Command!
    usage: /<command>
  game:
    description: Game options.
    permission: op
    permission-message: You do not have permission to use this Command!
    usage: /<command> [start|stop|team]
  lobby:
    description: Teleports you to the lobby.
    usage: /<command>
    aliases:
      - l
      - hub